pigeon/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# app_name= 'accounts'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('register/', views.register, name="register"),
    path('login/', views.LoginView.as_view(), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('verify/', views.verify_code, name="verify")
]

pigeon/pigeon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('payment/',include('payment.urls'), name='payment'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('admin/', admin.site.urls),
    path('', index, name="index")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pigeon/transactions/urls.py
from django.urls import path
from . import views
 
app_name = 'transactions'

urlpatterns = [
    path('create/',views.transaction_create, name="transaction_create"),
    path('<int:id>/created/', views.transaction_created, name="transaction_created"),
    path('', views.transaction_list, name="transaction_list"),
    path('<int:id>/detail', views.transaction_detail, name="transaction_detail"),
    path('<int:id>/preview', views.transaction_preview, name="transaction_preview"),
    path('accept-transaction/',views.TransactionAcceptanceView.as_view(), name="user_accept_transaction")
]

pigeon/accounts/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomUserManager
import datetime

class User(AbstractBaseUser):
    
    username = None
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(_('email address'), unique=True)
    phone = models.CharField(max_length=20)
    image = models.FileField(upload_to="media/", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    last_login = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        ordering = ['-created_at']

    def __str__(self) -> str:
        return self.email
    
    @property
    def is_superuser(self):
        return self.is_admin


    def has_perm(self, perm, obj=None):
       return self.is_admin
    
    def has_module_perms(self, app_label):
       return self.is_admin
    
   

    def save_last_login(self) -> None:
        self.last_login = datetime.now()
        self.save()


class Buyer(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True)
    
class Seller(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                primary_key=True
                                )

pigeon/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
import re

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    phone = forms.CharField(label="Phone number", max_length=20, required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name','email', 'phone']
    
    def clean_phone(self):
        """Validates number start with +254 or 0, then 9 digits"""
        cd = self.cleaned_data
        number = cd['phone']
        number_pattern = re.compile(r'^(?:\+254|0)\d{9}$')
        result = number_pattern.match(number)
        if result:
            if number.startswith('0'): 
                return '+254' + number[1:]
            return number
        
class VerifyForm(forms.Form):
    code = forms.CharField(label="Verification code",max_length=8, required=True, help_text='Enter code')


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class':"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"}
        ),
        label='Email address',
        max_length=100
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"}
        ),
        label='Password',
        max_length = 100
    )

pigeon/accounts/views.py
from django.shortcuts import render, redirect
from .models import User
from .forms import UserRegistrationForm, VerifyForm, CustomAuthenticationForm
from django.contrib.auth.decorators import login_required
from .decorators import verification_required
from django.contrib import messages
from .tasks import send_phone_verification
from .verify import verify_otp
from django.contrib.auth.views import LoginView



@login_required
# @verification_required
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def register(request):
    template_name = 'accounts/register.html'
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = form.save(commit=False)
            # Set the chosen password
            new_user.set_password(form.cleaned_data['password1'])
            # Save the User object
            new_user.save()
            send_phone_verification.delay(form.cleaned_data.get('phone'))
            return redirect("dashboard")
    return render(request, template_name, {'form': form})


@login_required
def verify_code(request):
    template_name = 'accounts/verify.html'
    if request.method == 'POST':
        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')
            if verify_otp(request.user.phone, code):
                request.user.is_verified = True
                request.user.save()
                return redirect('dashboard')
            else:
                messages.error(request, 'Invalid code provided')
    else:
        form = VerifyForm()
    return render(request, template_name, {'form': form})

class LoginView(LoginView):
    template_name = 'accounts/login.html'
    authentication_form = CustomAuthenticationForm

pigeon/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
  <h1>Dashboard</h1>
  <p>Welcome to your dashboard.</p>
  <a href="{% url "transactions:transaction_create" %}">New transaction</a>
  <a href="{% url "transactions:transaction_list" %}">My transactions</a>
{% endblock %}

pigeon/accounts/templates/accounts/login.html
{% extends "_base.html" %}
{% block title %}Login to your account {% endblock %}

{% block body %}

<div class="flex justify-center flex-col relative mx-4 pt-7">
  <div class="pb-6 pl-5 h-12 w-12 ">
    <svg class=" h-auto w-full" width="250" height="362" viewBox="0 0 250 362" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 288.633L125 216.598V360.668L0 288.633Z" fill="#5D20D2"/>
      <path d="M0 144.57L125 72.5352V216.605L0 144.57Z" fill="#5D20D2"/>
      <path d="M125 72.5352L0 144.57V0.5L125 72.5352Z" fill="#5D20D2"/>
      <path d="M125 216.605L0 288.641V144.562L125 216.605Z" fill="#5D20D2"/>
      <path d="M0 288.535V144.465L125 216.5L0 288.535Z" fill="#C02AD1"/>
      <path d="M0 144.57L125 72.5352V216.605L0 144.57Z" fill="#C02AD1"/>
      <path d="M249.828 144.504L124.832 216.539V72.4648L249.828 144.504Z" fill="#C02AD1"/>
      </svg>
      
  </div>
  <div class="bg-white rounded-xl pt-8 px-5 flex justify-start flex-col  shadow-lg">
{% if form.errors %}
<p>
  Your username and password didn't match.
  Please try again.
</p>
{% else %}
<p class="text-[#192851] tracking-tight text-2xl font-medium leading-8">Sign in to your account</p>
{% endif %}
<div class="mt-5 pb-3">
  <form method="post"  action="{% url 'login' %}">
    {% csrf_token %}
    
    {{ form.as_p}}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class=" text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'register' %}">Create an account</a> </p>
</div>
</div>
</div>

{% endblock %}

pigeon/accounts/templates/accounts/logout.html
{% extends "_base.html" %}
{% block title %}Logged out{% endblock %}
{% block body %}
  <h1>Logged out</h1>
  <p>
    You have been successfully logged out.
    You can <a href="{% url "login" %}">log-in again</a>.
  </p>
{% endblock %}

pigeon/accounts/templates/accounts/register.html
{% extends '_base.html' %}

{% block body %}
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

pigeon/accounts/templates/accounts/verify.html
{% extends 'base.html' %}

{% block content %}
  <h1>Verify your account</h1>
  {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Verify</button>
  </form>
{% endblock %}