pigeon/payment/urls.py
from django.urls import path

from . import views

app_name="payment"

urlpatterns = [
    path("checkout/", views.MpesaCheckout.as_view(), name="checkout"),
    path("callback/", views.MpesaCallBack.as_view(), name="callback"),
]

pigeon/pigeon/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('payment/',include('payment.urls'), name='payment'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('transactions/', include('transactions.urls'), name='transactions'),
    path('admin/', admin.site.urls),
    path('', index, name="index")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pigeon/transactions/urls.py
from django.urls import path
from . import views
 
app_name = 'transactions'

urlpatterns = [
    path('create/',views.transaction_create, name="transaction_create"),
    path('<int:id>/created/', views.transaction_created, name="transaction_created"),
    path('', views.transaction_list, name="transaction_list"),
    path('<int:id>/detail', views.transaction_detail, name="transaction_detail"),
    path('<int:id>/preview', views.transaction_preview, name="transaction_preview"),
    path('accept-transaction/',views.TransactionAcceptanceView.as_view(), name="user_accept_transaction")
]

pigeon/transactions/models.py
from django.db import models
from accounts.models import Buyer, Seller, User
from django.urls import reverse, NoReverseMatch
from .utils import create_new_ref_number

class Category(models.Model):
    name = models.CharField(max_length=200)
  
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

class Transaction(models.Model):
    PENDING = 'P'
    IN_PROGRESS = 'IP'
    COMPLETED = 'C'
    CANCELED = 'X'
    ACTION_REQUIRED = 'AR'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (IN_PROGRESS, 'In Progress'),
        (COMPLETED, 'Completed'),
        (CANCELED, 'Canceled'),
        (ACTION_REQUIRED, 'Action Required'),
    ]

    FEE_PAYMENT_CHOICES = [
        ("buyer", 'Buyer'),
        ("seller", 'Seller'),
        ("split", 'Split')
    ]
    
    amount = models.DecimalField(max_digits=10,decimal_places=2, null=True, blank=True)
    title = models.CharField(max_length=255, null=False, blank=False)
    shareable_url = models.CharField(max_length=255, null=True, blank=True)
    category = models.ForeignKey(Category,
                                 related_name='transactions',
                                 on_delete=models.CASCADE)
    buyer = models.ForeignKey(Buyer,
                              on_delete=models.SET_NULL,
                              related_name="buyer_transactions",
                              null=True,
                              blank=True)
    seller = models.ForeignKey(Seller,
                               on_delete=models.SET_NULL,
                               related_name='seller_transactions',
                               null=True,
                               blank=True)
    initiator = models.ForeignKey(User,
                                  on_delete=models.CASCADE,
                                  related_name='initiated_transactions')
    initiator_role = models.CharField(max_length=10, choices=[('buyer', 'Buyer'), ('seller', 'Seller')])
    action_description = models.TextField(blank=True, null=True)  
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=PENDING)
    reference_no = models.CharField(blank=True, unique=True, editable=False, max_length=10, default=create_new_ref_number)
    fee_paid_by = models.CharField(choices=FEE_PAYMENT_CHOICES, max_length=6)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title
    
    def save(self, *args, **kwargs):
        # Generate the shareable URL and save it when the transaction is saved
        if not self.id:
            super().save(*args, **kwargs)
        if not self.shareable_url:
            try:
                self.shareable_url = reverse('transactions:transaction_preview', args=[str(self.id)])
            except NoReverseMatch as e:
                print(f"Error generating URL: {e}")
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("transactions:transaction_detail",args = [self.id])
    

class ProductFile(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, related_name='product_files')
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='product_files/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Product(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    inspection_period = models.IntegerField(default=1, null=False, blank=False)
    transaction = models.ForeignKey(Transaction,
                                related_name='products',
                                on_delete=models.CASCADE
                                )
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id'])
        ]

    def __str__(self) -> str:
        return self.name


class TransactionHistory(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    action_timestamp = models.DateTimeField(auto_now_add=True)
    action_description = models.TextField()

pigeon/transactions/forms.py
from .models import Product, Transaction, ProductFile
from django import forms


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['initiator_role', 'title', 'amount', 'category' ]
        widgets = {
            "initiator_role" : forms.RadioSelect( attrs={'class': "role-select"})
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['transaction']

class AcceptanceForm(forms.Form):
    transaction = forms.ModelChoiceField(
        queryset=Transaction.objects.all(),
        widget=forms.HiddenInput)

class ProductFileForm(forms.ModelForm):
    class Meta:
        model = ProductFile
        exclude = ['created', 'updated', 'transaction']

class RecepientDetailsForm(forms.Form):
    email =forms.EmailField()
    name = forms.CharField(max_length=50)

pigeon/transactions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import TransactionForm, ProductForm, AcceptanceForm, ProductFileForm, RecepientDetailsForm
from accounts.models import Seller, Buyer, User
from django.contrib.auth.decorators import login_required
from .models import Transaction, TransactionHistory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from payment.forms import MpesaSTKForm
from .tasks import send_confirmation_email




@login_required
def transaction_list(request):
    buyer_instance = get_object_or_404(Buyer, user_id=request.user.id)
    seller_instance = get_object_or_404(Seller, user_id=request.user.id)
    transactions = Transaction.objects.filter(
        Q(initiator = request.user) |
        Q(seller = seller_instance) | 
        Q(buyer = buyer_instance)
    )
    return render(request, "transactions/list.html", {'transactions': transactions})

@login_required
def transaction_detail(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    product_list = transaction.products.all()
    return render(request, "transactions/transaction/detail.html", {'transaction': transaction, 'product_list':product_list, 'MpesaSTKForm': MpesaSTKForm})


def transaction_preview(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    product_list = transaction.products.all()
    acceptance_form = AcceptanceForm(initial={'transaction':transaction})

    return render(request, "transactions/transaction/preview.html", {'transaction': transaction, 'product_list':product_list, 'acceptance_form': acceptance_form})

@login_required
def transaction_create(request):
    current_user = get_object_or_404(User, id=request.user.id)
    
    if request.method == 'POST':
        
        transaction_form = TransactionForm(request.POST, prefix="transaction")
        
        if transaction_form.is_valid():
            transaction_data = transaction_form.cleaned_data
            # Create the transaction instance first
            transaction = transaction_form.save(commit=False)
            if transaction_data["initiator_role"] == 'buyer':
                # Returns a tuple of (object: object, boolean: created)
                buyer_instance = Buyer.objects.get_or_create(user_id=request.user.id)
                # Access the returned instance object
                transaction.buyer = buyer_instance[0]
                
            else:
                seller_instance = Seller.objects.get_or_create(user_id=request.user.id)
                transaction.seller = seller_instance[0]
            transaction.initiator = current_user
            transaction.status = Transaction.ACTION_REQUIRED
            transaction.action_description = "Please review and accept the terms."
            transaction.save()


            if request.POST['submission_type'] == 'file':
                product_file_form = ProductFileForm(request.POST, request.FILES, prefix="product_file")
                product_file = product_file_form.save(commit=False)
                product_file.transaction = transaction
                product_file.save()
            elif request.POST['submission_type'] == 'manual':
                product_form = ProductForm(request.POST, prefix="product")
                product = product_form.save(commit=False)
                product.transaction = transaction
                product.save()


            TransactionHistory.objects.create(
            transaction=transaction,
            user=current_user,
            action_description="Transaction was created by {}: ({})".format(transaction_data['initiator_role'],current_user)
            )
            
            recepient_details_form = RecepientDetailsForm(request.POST, prefix="recepient")
            if recepient_details_form.is_valid():
                recepient_details = recepient_details_form.cleaned_data

            transaction_data = {
                'title' : transaction.title,
                'amount' : transaction.amount,
                'role' : transaction.initiator_role,
                'reference_no': transaction.reference_no,
                'shareable_url': transaction.shareable_url
            }
            send_confirmation_email.delay(transaction=transaction_data,
                                          sender_name=current_user.first_name, 
                                          sender_email=current_user.get_username(),
                                          recepient_mail=recepient_details['email'],
                                          recepient_name=recepient_details['name'] )
            
            return redirect(reverse("transactions:transaction_created", args=[transaction.id]))

    else:
        transaction_form = TransactionForm(prefix="transaction")
        product_form = ProductForm(prefix="product")
        product_file_form = ProductFileForm(prefix="product_file")
        recepient_details_form = RecepientDetailsForm(prefix="recepient")
    
    return render(request, 
                  'transactions/transaction/create.html',
                  {'transaction_form': transaction_form,
                   'product_form':product_form,
                   'product_file_form': product_file_form,
                   'recepient_details_form': recepient_details_form})

@login_required
def transaction_created(request, id):
    transaction = get_object_or_404(Transaction, id= id)
    return render(request, 'transactions/transaction/created.html', {'transaction': transaction})

class TransactionAcceptanceView(LoginRequiredMixin, FormView):
    transaction = None
    form_class = AcceptanceForm

    def form_valid(self, form):
        self.transaction = form.cleaned_data['transaction']

        if form.is_valid():
            if self.transaction.seller == None:
                 # If seller is None, create a Seller instance and associate it with the transaction
                seller_instance, created = Seller.objects.get_or_create(user_id=self.request.user.id)
                self.transaction.seller = seller_instance
            else:
                # If seller is already assigned, assume we are updating the buyer
                buyer_instance, created = Buyer.objects.get_or_create(user_id=self.request.user.id)
                self.transaction.buyer = buyer_instance
        else:
            print(form.errors)


        self.transaction.save()
                
        self.transaction.status = Transaction.ACTION_REQUIRED
        self.transaction.action_description = "Please pay for the for transaction."


        TransactionHistory.objects.create(
            transaction=self.transaction,
            user=self.request.user,
            action_description="Transaction was accepted by: ({})".format(self.request.user)
        )
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('transactions:transaction_detail',
                            args=[self.transaction.id])

pigeon/transactions/templates/transactions/transaction/create.html
{% extends "base.html" %}
{% load static %}
{% load compress %}
{% block css %}
{% compress css %}
<link rel="stylesheet" href="{% static 'transactions/css/transaction.css' %}" >
{% endcompress %}
{% endblock %}
{% block title %}
    New transaction
{% endblock %}

{% block content %}

<div class="w-full max-w-2xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">

<h1 class="text-xl font-semibold capitalize leading-none text-gray-900 dark:text-white mb-3">New Escrow Transaction</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="divide-y divide-gray-200 dark:divide-gray-700">
        <div class="space-y-2 mb-5">
    <h3>Transaction details</h3>
    {{ transaction_form.as_p }}

    <div class="">
        <h3 class="text-center capitalize font-medium text-sm text-gray-500">Payment information</h3>
        <span class="flex justify-between">
            <h3>Transaction amount</h3>
            <p id="transaction_amount">0.00</p>
        </span>
        <span class="flex justify-between">
            <h3 class="">Escrow fees 1.8%</h3>
            <p id="transaction_fee_amount">0.00</p>
        </span>
        <span class="flex justify-between">
            <h3 class="">Final amount to be paid</h3>
            <p id="transaction_total_payable">0.00</p>
        </span>
    </div>
</div>

<div class="space-y-2 mb-5">
    <h3 class="font-medium">Product details</h3>
    <input type="radio" name="submission_type" value="file" checked> Submit File
    <div id="file-form">
        {{ product_file_form.as_p }}
    </div>
    
    <input type="radio" name="submission_type" value="manual"> Submit Manual Input
    <div id="product-form" style="display: none;">
        {{ product_form.as_p }}    
    </div>
    
</div>

<div class="space-y-2 mb-5">
    <h3 class="font-medium">Recepient details</h3>
   
    <div >
        {{ recepient_details_form.as_p }}
    </div>
    

    
</div>


</div>
    <button class="bg-blue-500 text-white rounded-lg px-5 py-2.5" type="submit">Create transaction</button>

</form>
</div>

{% endblock %}

{% block script %}
{% compress js %}
<script>

   document.addEventListener('DOMContentLoaded', function() {

   const amountInput = document.getElementById("id_transaction-amount");
   const amount = document.getElementById("transaction_amount")
   const fees = document.getElementById("transaction_fee_amount")
   const payableAmount = document.getElementById("transaction_total_payable")
   amountInput.addEventListener("change", (e) => {
    let value = parseFloat(e.target.value)
    console.log(typeof value)
    amount.textContent = value.toFixed(2)
    // calculate escrow fees 
    let transactionFee = value * (1.8/100)
    fees.textContent = transactionFee.toFixed(2)

    // calculate total payable amount for the transaction
    let totalAmount = value + transactionFee
    payableAmount.textContent = totalAmount.toFixed(2)
   })

   // display product form or product file form
        const submissionTypeInputs = document.getElementsByName('submission_type');
        

        for (var i = 0; i < submissionTypeInputs.length; i++) {
            submissionTypeInputs[i].addEventListener('change', function() {
                var selectedValue = this.value;

                if (selectedValue === 'file') {
                    document.getElementById('file-form').style.display = 'block';
                    document.getElementById('product-form').style.display = 'none';

                    // remove required attribute in the product form
                    document.getElementsByName("product-name")[0].removeAttribute('required')
                    document.getElementsByName("product-description")[0].removeAttribute('required')
                    document.getElementsByName("product-price")[0].removeAttribute('required')

                    document.getElementsByName("product_file-title")[0].setAttribute('required', 'required')
                    document.getElementsByName("product_file-file")[0].setAttribute('required', 'required')
                } else if (selectedValue === 'manual') {
                    document.getElementById('file-form').style.display = 'none';
                    document.getElementById('product-form').style.display = 'block';

                    document.getElementsByName("product-name")[0].setAttribute('required', 'required')
                    document.getElementsByName("product-description")[0].setAttribute('required', 'required')
                    document.getElementsByName("product-price")[0].setAttribute('required', 'required')

                    document.getElementsByName("product_file-title")[0].removeAttribute('required')
                    document.getElementsByName("product_file-file")[0].removeAttribute('required')
                }
            });
        }


    });

   
</script>
{% endcompress %}
{% endblock %}

pigeon/transactions/templates/transactions/transaction/created.html
{% extends "base.html" %}
{% load static %}
{% load compress %}
{% block title %}
    New transaction
{% endblock %}

{% block content %}



<div class="w-full p-4 text-center bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
    <h5 class="mb-2 text-3xl font-bold text-gray-900 dark:text-white">Your escrow request has been sent.</h5>
    <p class="mb-5  text-gray-500 sm:text-lg dark:text-gray-400">We will update once they have agreed to the escrow request.</p>
    
   
        <div  class="flex items-center p-3  mb-3 font-bold text-gray-900 rounded-lg bg-gray-50  dark:bg-gray-600  dark:text-white">
        <span id="shareable_url" class="flex-1 ms-3 whitespace-nowrap">http://127.0.0.1:8000{{ transaction.shareable_url }}</span>
        <span id="copy-text" class="hover:bg-gray-200 p-3 hover:shadow cursor-pointer dark:hover:bg-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
          </svg>
          
        </div>
        </span>
        <span class="text-xs">Copy the following url and paste in chats on social media</span>
     
    
    <div class="items-center mt-3 justify-center space-y-4 sm:flex sm:space-y-0 sm:space-x-4 rtl:space-x-reverse">
        <a href="#" class="w-full sm:w-auto bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 text-white rounded-lg inline-flex items-center justify-center px-4 py-2.5 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700">
            <div class="text-left rtl:text-right">
                <p>Back to home</p>
            </div>
        </a>
    </div>
</div>


{% endblock %}

{% block script %}
{% compress js %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById("copy-text").addEventListener('click', () => {
            let textCopy = document.getElementById("shareable_url").textContent;

            navigator.clipboard.writeText(textCopy).then(()=> {
                alert("Text copied")
            }, () => {
                alert("Not copied")
            })
        })

    })
</script>
{% endcompress %}

{% endblock %}

pigeon/transactions/templates/transactions/transaction/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ transaction.title }}
{% endblock %}
{% block content %}
     <h1 class="font-bold text-xl mb-6 uppercase">esc - {{transaction.reference_no}}</h1>

     {% if transaction.status == 'AR' %}

      <div id="alert-additional-content-4" class="p-4 mb-4 text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300 dark:border-yellow-800" role="alert">
        <div class="flex items-center">
          <svg class="flex-shrink-0 w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
          </svg>
          <span class="sr-only">Info</span>
          <h3 class="text-lg font-medium">This is an action required alert</h3>
        </div>
        <div class="mt-2 mb-4 text-sm">
          {{ transaction.action_description }}        </div>

      </div>

     {% endif %}

     <div>
        <form action="{% url "payment:checkout" %}" method="post">
            {% csrf_token %}
        {{MpesaSTKForm.as_p}}
        <input type="submit" value="Make payment" />
    </form>
     </div>

      <p class="font-semibold text-lg mb-4">Transaction details</p>
      <div class="grid gap-6 grid-cols-4 mb-4 [&>div>p]:text-sm">
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs">transaction number</span>
            <p class="uppercase">{{transaction.reference_no}}</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs">amount </span>
            <p>{{ transaction.amount }}</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs">initiator </span>
            <p>{{ transaction.initiator }}</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs"> date</span>
            <p>04/12/2023</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs"> title</span>
            <p>{{ transaction.title }}</p>
        </div>
   
   
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs"> buyer</span>
            <p>{{ transaction.buyer.user }}</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs"> seller</span>
            <p> {{ transaction.seller.user }}</p>
        </div>
        <div class="flex flex-col space-y-1.5">
            <span class="uppercase text-xs"> status</span>
            <span class="bg-gray-100 text-gray-800 w-fit text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-gray-700 dark:text-gray-300">{{transaction.status}}</span>

        </div>

      </div>
    
      <div class="mb-6">
    <p class="font-semibold text-lg mb-4">Transaction products</p>
    <div class="grid grid-cols-5 [&>span]:uppercase text-xs mb-2">
        <span>product name</span>
        <span>category</span>
        <span>price</span>
        <span>description</span>
        <span>inspection period</span>
    </div>
    {% for product in product_list %}
    <div class="border-t border-gray-100 rounded p-2 grid grid-cols-5 text-sm">
    <p>{{ product.name }}</p>
    <p>{{ product.category }}</p>
    <p>{{ product.price }}</p>
    <p>{{ product.description }}</p>
    <p>{{ product.inspection_period }} days</p>
</div>
    {% endfor %}

</div>
<div class="mb-6">
    <p class="font-semibold text-lg mb-4">History </p>

<ol class="relative border-s border-gray-200 dark:border-gray-700">
  {% for history_entry in transaction.transactionhistory_set.all %}

    <li class="ms-4 relative">
        <div class="absolute w-3 h-3 bg-gray-200 rounded-full bottom-1 -start-[22px] border border-white dark:border-gray-900 dark:bg-gray-700"></div>
        <span class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">{{ history_entry.action_timestamp }}</span>
        <p class="text-sm font-normal text-gray-500 dark:text-gray-400">{{ history_entry.action_description }} 	</p>
    </li>


    {% endfor %}
</ol>



</div>
    

{% endblock %}

pigeon/transactions/templates/transactions/transaction/preview.html
{% extends '_base.html' %}
{% block title %}
 {{ transaction.title }} | Confirmation screen
{% endblock %}

{% block body %}


<div class="w-full mx-auto mt-20 max-w-md p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
    <div class=" mb-4">
        <div class="flex items-center text-gray-500 uppercase gap-2 text-sm">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75M15 10.5a3 3 0 11-6 0 3 3 0 016 0zm3 0h.008v.008H18V10.5zm-12 0h.008v.008H6V10.5z" />
              </svg>
              <span>Amount</span>              
        </div>
        <p class="text-lg font-medium">{{ transaction.amount }}

            <span class="text-lg text-gray-400">KES</span>
        </p>
        

   </div>
   <div class="flow-root">
    <div class="mb-4">
        <div class="border-b border-gray-200">
        <p class="font-medium mb-2">Transaction details</p>
    </div>

    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Title</span>
        <p class="flex-1">{{ transaction.title}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Initiator</span>
        <p class="flex-1">{{ transaction.initiator}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Date created</span>
        <p class="flex-1">{{ transaction.created }}</p>
    </div>

    </div>

    <div class="mb-4">
        <div class="border-b border-gray-200">
        <p class="font-medium mb-2">Transaction products</p>
    </div>

    {% for product in product_list %}

    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Product name</span>
        <p class="flex-1">{{ product.name}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Price</span>
        <p class="flex-1">{{ product.price}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Description</span>
        <p class="flex-1">{{ product.description}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Category</span>
        <p class="flex-1">{{ product.category}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Inspection period</span>
        <p class="flex-1">{{ product.inspection_period}}</p>
    </div>

    {% endfor %}


    </div>

    <div class="mb-4">
        <div class="border-b border-gray-200">
        <p class="font-medium mb-2">Transaction terms</p>
    </div>

    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Seller</span>
        <p class="flex-1">{{ transaction.seller.user}}</p>
    </div>
    <div class="flex items-center py-1 text-sm">
        <span class="flex-1 text-gray-400">Buyer</span>
        <p class="flex-1">{{ transaction.buyer.user}}</p>
    </div>
        

    </div>

   </div>

   {% if request.user.is_authenticated %}
   <form action="{% url "transactions:user_accept_transaction" %}" method="post">
    {% csrf_token %}
    {{acceptance_form}}
    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Accept transaction</button>
   </form>
   {% else %}
   <a href="{% url "login" %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center">Sign in to continue</a>
   {% endif %}
</div>

{% endblock %}